### ISSUE TITLE
Doubles with zero fraction-part/mantissa are converted to integers upon serialization

### ISSUE THREAD

**Issue by thammegowda** [douglascrockford/JSON-java#134]
```java
    @Test
    public void testSerialization() throws Exception {

        final String A_DOUBLE = "aDouble";
        final String B_DOUBLE = "bDouble";
        final double aDouble = 3.0;
        final double bDouble = 3.1;
        JSONObject object = new JSONObject();
        object.put(A_DOUBLE, aDouble);
        object.put(B_DOUBLE, bDouble);

        assertEquals(aDouble, object.get(A_DOUBLE)); // PASS
        assertEquals(bDouble, object.get(B_DOUBLE)); // PASS

        String serializedString = object.toString();
        JSONObject deserialized = new JSONObject(serializedString);
        assertEquals(bDouble, deserialized.get(B_DOUBLE)); // PASS
        assertEquals(aDouble, deserialized.get(A_DOUBLE)); // Fail : expected=3.0(double) and actual=3 (int)

    }
```

**Comment by stleary** [comment]
Thanks, I added a new unit test to document the behavior. See  https://github.com/stleary/JSON-Java-unit-test, JSONObjectTest.java, unexpectedDoubleToIntConversion() .  

However, I don't see how this is an error that needs to be fixed. Feel free to open a new issue if you want, and explain how you think the existing behavior is incorrect, and how you would fix it.

**Comment by boekhold** [comment]
Hi,

I'm running into this issue as well. As I see it, the problem here is that the field in the original JSON is clearly intended to be a float/double value, but on serialization the trailing ".0" is dropped, so the value looks like an integer.

OK, semantically 3.0 and 3 are the same value. The problem is when you then deserialize the JSON again: most Java JSON libraries will parse "3" as an Integer, while the source code would probably expect a Doubel/BigDecimal instead (since the value started out as "3.0"). I'm actually running into this issue at the moment in a case where I read an input JSON that has values that are "0.0". I'm transforming the structure of the JSON document and serialize it back out. I'm then comparing (using zjsonpatch) against expected result, which is a hand-crafted JSON file that has "0.0" as the expected value. But JSONObject.toString() produces "0" instead, which is not considered equal.

zjsonpatch uses Jackson JsonNode.equals() to compare 2 nodes, and that equals() implementation doesn't consider 0 and 0.0 to be the same. "0" is parsed as a java.lang.Integer, "0.0" as java.lang.Double, and JsonNode.equals() compares the class type of the objects being compared as well.

**Comment by johnjaylward** [comment]
json does not differentiate between number types though.  In json it's just a number. This sounds like an error in the tool you are using to compare.
