### ISSUE TITLE
toString(int indentFactor)

### ISSUE THREAD

**Issue by ukby1234** [douglascrockford/JSON-java#148]
Please change the '\n' to platform-independent carriage return character, System.getProperty("line.separator")

**Comment by stleary** [comment]
Since this is released code, proposals for changes to existing behavior have a high bar for acceptance. This does not look like a feature enhancement or bug fix. Agreed that it would be a convenience for some, and it does not impact essential functionality. However, it might be problematic for some existing users that expect their output format will not change in a new release.  Unless a case can be made why this change is needed, I don't think we should include it at the present time.
